# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-24 23:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IridiumData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transmit_time', models.DateTimeField()),
                ('iridium_latitude', models.FloatField()),
                ('iridium_longitude', models.FloatField()),
                ('iridium_cep', models.FloatField()),
                ('momsn', models.IntegerField()),
                ('imei', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Packet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('packet_id', models.IntegerField()),
                ('version', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='iridiumdata',
            name='global_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groundstationapp.Packet'),
        ),
    ]
