# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-24 23:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groundstationapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlowMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gps_latitude', models.FloatField()),
                ('gps_longitude', models.FloatField()),
                ('gps_altitude', models.FloatField()),
                ('gps_time', models.DateTimeField()),
                ('global_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groundstationapp.Packet')),
            ],
        ),
    ]
