# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-24 23:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groundstationapp', '0005_conductivitydata'),
    ]

    operations = [
        migrations.CreateModel(
            name='FastMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_id', models.IntegerField()),
                ('vert1', models.IntegerField()),
                ('vert2', models.IntegerField()),
                ('vertD', models.IntegerField()),
                ('compassX', models.IntegerField()),
                ('compassY', models.IntegerField()),
                ('compassZ', models.IntegerField()),
                ('horiz1', models.IntegerField()),
                ('horiz2', models.IntegerField()),
                ('horizD', models.IntegerField()),
                ('global_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groundstationapp.Packet')),
            ],
        ),
    ]
