# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-25 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groundstationapp', '0006_fastmeasurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packet',
            name='packet_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='packet',
            name='version',
            field=models.IntegerField(null=True),
        ),
    ]
