# Generated by Django 2.2.2 on 2019-07-01 01:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groundstationapp', '0008_auto_20190613_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='slowmeasurement',
            name='cond_gps_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 1, 1, 34, 33, 127741)),
            preserve_default=False,
        ),
    ]
