# Generated by Django 2.2.2 on 2019-07-02 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groundstationapp', '0009_slowmeasurement_cond_gps_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductivitydata',
            name='global_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groundstationapp.SlowMeasurement'),
        ),
    ]
