# Generated by Django 2.2.2 on 2019-07-02 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groundstationapp', '0010_auto_20190702_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slowmeasurement',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
