# Generated by Django 2.2.3 on 2019-07-07 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groundstationapp', '0011_auto_20190702_0127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('yikes', models.IntegerField()),
                ('ballast', models.IntegerField()),
                ('cutdown', models.IntegerField()),
                ('global_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groundstationapp.Packet')),
            ],
        ),
    ]
