# Generated by Django 2.2.3 on 2019-08-22 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groundstationapp', '0012_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('processing_duration', models.DurationField()),
                ('forwarded_for_address', models.TextField()),
                ('forwarded_host_address', models.TextField()),
                ('forwarded_server_address', models.TextField()),
                ('remote_address', models.TextField()),
                ('raw_request_data', models.TextField()),
                ('response_duration', models.DurationField()),
                ('response_errors', models.TextField()),
                ('response_status_code', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='supdata',
            name='sub_id',
            field=models.BigIntegerField(),
        ),
        migrations.CreateModel(
            name='IridiumTransmission',
            fields=[
                ('parent_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='child_transmission', serialize=False, to='groundstationapp.Request')),
                ('time', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('cep', models.FloatField()),
                ('momsn', models.IntegerField()),
                ('imei', models.BigIntegerField()),
                ('transmitted_via_satellite', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Measurements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('vert1', models.IntegerField()),
                ('vert2', models.IntegerField()),
                ('vertD', models.IntegerField()),
                ('compassX', models.IntegerField()),
                ('compassY', models.IntegerField()),
                ('compassZ', models.IntegerField()),
                ('horiz1', models.IntegerField()),
                ('horiz2', models.IntegerField()),
                ('horizD', models.IntegerField()),
                ('parent_packet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groundstationapp.Packet')),
            ],
        ),
        migrations.CreateModel(
            name='ConductivityMeasurements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('vert1', models.IntegerField()),
                ('vert2', models.IntegerField()),
                ('parent_packet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groundstationapp.Packet')),
            ],
        ),
        migrations.CreateModel(
            name='PacketV6',
            fields=[
                ('parent_transmission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='child_packet', serialize=False, to='groundstationapp.IridiumTransmission')),
                ('yikes_status', models.IntegerField()),
                ('mcu_id', models.IntegerField()),
                ('version', models.IntegerField()),
                ('sequence_id', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.FloatField()),
                ('ballast_status', models.IntegerField()),
                ('cutdown_status', models.IntegerField()),
                ('conductivity_time', models.DateTimeField()),
                ('satellites_count', models.IntegerField()),
                ('rockblock_signal_strength', models.IntegerField()),
                ('commands_count', models.IntegerField()),
                ('altimeter_temp', models.IntegerField()),
                ('altimeter_pressure', models.IntegerField()),
                ('positive_7v_battery_voltage', models.IntegerField()),
                ('negative_7v_battery_voltage', models.IntegerField()),
                ('positive_3v6_battery_voltage', models.IntegerField()),
                ('current_draw_7v_rail', models.IntegerField()),
                ('current_draw_3v3_rail', models.IntegerField()),
                ('battery_temp', models.IntegerField()),
                ('mcu_temp', models.IntegerField()),
                ('compass_temp', models.IntegerField()),
                ('adc1_temp', models.IntegerField()),
                ('adc2_temp', models.IntegerField()),
                ('external_temp', models.IntegerField()),
                ('rockblock_temp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RawPacket',
            fields=[
                ('parent_transmission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='child_raw_packet', serialize=False, to='groundstationapp.IridiumTransmission')),
                ('data', models.BinaryField()),
                ('hexdata', models.TextField()),
            ],
        ),
    ]
