# Generated by Django 2.2.3 on 2019-08-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groundstationapp', '0013_auto_20190822_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='iridiumtransmission',
            name='device_type',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='iridiumtransmission',
            name='iridium_session_status',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='iridiumtransmission',
            name='serial',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rawpacket',
            name='data',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='rawpacket',
            name='hexdata',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='processing_duration',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='raw_request_data',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='response_duration',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='response_errors',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='response_status_code',
            field=models.TextField(null=True),
        ),
    ]
