# Generated by Django 2.2.2 on 2021-06-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groundstationapp', '0014_auto_20210609_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='UplinkRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imei', models.BigIntegerField()),
                ('time', models.DateTimeField()),
                ('password', models.TextField(null=True)),
                ('message', models.TextField(null=True)),
            ],
        ),
    ]
