# Generated by Django 2.2.3 on 2019-08-24 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groundstationapp', '0014_auto_20190823_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packetv6',
            name='altimeter_pressure',
            field=models.BigIntegerField(),
        ),
    ]
