# Generated by Django 2.2.3 on 2019-08-24 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groundstationapp', '0015_auto_20190824_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductivitymeasurements',
            name='parent_packet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groundstationapp.PacketV6'),
        ),
        migrations.AlterField(
            model_name='measurements',
            name='parent_packet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groundstationapp.PacketV6'),
        ),
    ]
