# Generated by Django 2.2.2 on 2021-06-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groundstationapp', '0015_uplinkrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='uplinkrequest',
            name='success',
            field=models.BooleanField(default=True),
        ),
    ]
