# Generated by Django 2.2.3 on 2019-08-27 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groundstationapp', '0016_auto_20190824_0417'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConductivityMeasurementsUnits',
            fields=[
                ('parent_conductivity_measurements', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='child_conductivity_measurements_units', serialize=False, to='groundstationapp.Measurements')),
                ('time', models.DateTimeField()),
                ('vert1', models.FloatField()),
                ('vert2', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementsUnits',
            fields=[
                ('parent_measurements', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='child_measurements_units', serialize=False, to='groundstationapp.Measurements')),
                ('time', models.DateTimeField()),
                ('vert1', models.FloatField()),
                ('vert2', models.FloatField()),
                ('vertD', models.FloatField()),
                ('compassX', models.FloatField()),
                ('compassY', models.FloatField()),
                ('compassZ', models.FloatField()),
                ('horiz1', models.FloatField()),
                ('horiz2', models.FloatField()),
                ('horizD', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PacketV6Units',
            fields=[
                ('parent_packet_v6', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='child_packet_v6_units', serialize=False, to='groundstationapp.IridiumTransmission')),
                ('yikes_status', models.TextField(null=True)),
                ('time', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.FloatField()),
                ('ballast_status', models.TextField(null=True)),
                ('cutdown_status', models.TextField(null=True)),
                ('rockblock_signal_strength', models.FloatField()),
                ('altimeter_temp', models.FloatField()),
                ('altimeter_pressure', models.FloatField()),
                ('positive_7v_battery_voltage', models.FloatField()),
                ('negative_7v_battery_voltage', models.FloatField()),
                ('positive_3v6_battery_voltage', models.FloatField()),
                ('current_draw_7v_rail', models.FloatField()),
                ('current_draw_3v3_rail', models.FloatField()),
                ('battery_temp', models.FloatField()),
                ('mcu_temp', models.FloatField()),
                ('compass_temp', models.FloatField()),
                ('adc1_temp', models.FloatField()),
                ('adc2_temp', models.FloatField()),
                ('external_temp', models.FloatField()),
                ('rockblock_temp', models.FloatField()),
            ],
        ),
    ]
