# Generated by Django 2.2.3 on 2019-08-27 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groundstationapp', '0018_auto_20190827_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductivitymeasurementsunits',
            name='parent_conductivity_measurements',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='child_conductivity_measurements_units', serialize=False, to='groundstationapp.ConductivityMeasurements'),
        ),
        migrations.AlterField(
            model_name='packetv6units',
            name='parent_packet_v6',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='child_packet_v6_units', serialize=False, to='groundstationapp.PacketV6'),
        ),
    ]
